# Generated by Django 3.0.6 on 2020-05-10 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0002_auto_20200510_0448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
