# Generated by Django 3.0.6 on 2020-05-12 09:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0002_auto_20200510_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='UUID',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
