# Generated by Django 3.0.6 on 2020-05-14 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0002_auto_20200510_0448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='UUID',
        ),
    ]
