# Generated by Django 3.0.6 on 2020-05-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0005_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='number',
            field=models.CharField(blank=True, max_length=60, null=True, unique=True),
        ),
    ]
