# Generated by Django 3.0.6 on 2020-05-10 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0006_userprofile_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='number',
        ),
    ]
