# Generated by Django 3.0.6 on 2020-05-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzapi', '0007_remove_userprofile_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
